CREATE TABLE job_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_url VARCHAR(2048),
    job_type VARCHAR(50) NOT NULL,
    location VARCHAR(255),
    salary_min INTEGER,
    salary_max INTEGER,
    date_applied DATE,
    deadline DATE,
    status VARCHAR(50) NOT NULL,
    notes VARCHAR(5000)

    CONSTRAINT chk_job_type
        CHECK (job_type IN (
            'INTERNSHIP',
            'PLACEMENT',
            'GRADUATE',
            'FULL_TIME',
            'PART_TIME'
        )),

    CONSTRAINT chk_job_status
        CHECK (status IN (
            'SAVED',
            'APPLIED',
            'ASSESSMENT',
            'INTERVIEW',
            'OFFER',
            'REJECTED',
            'WITHDRAWN'
        )),

    CONSTRAINT chk_salary_min
        CHECK (salary_min >= 0),

    CONSTRAINT chk_salary_max
        CHECK (salary_max >= 0),

    CONSTRAINT chk_salary_range
        CHECK ( salary_min IS NULL
            OR salary_max IS NULL
            OR salary_min <= salary_max
            )
);